# Generated by Django 2.1.5 on 2019-02-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('verfiypassword', models.CharField(max_length=20)),
                ('registratime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'email',
                'ordering': ['registratime'],
            },
        ),
    ]
